### ISSUE TITLE
Map Loading

### ISSUE THREAD

**Issue by arqueffe** [francoisschwarzentruber/cmapf-gui#5]
- Initialisation is wrong; the map selected is not the one displayed.
- ~~The graphml are listed in the list : move the files and modify code *OR* **filter in the list**.~~
- The previous animation is still displayed after changing map.

**Comment by arqueffe** [comment]
Unlisted graphml files: commit a820735

**Comment by francoisschwarzentruber** [comment]
The previous animation disappears now when changing map.
